main: com.sonorous.SonorousAbilities
name: SonorousAbilities
author: SonorousMC
version: 1.0.0
api-version: '1.20'
depend: [ NDatabase, WorldGuard ]
commands:
  sonorous:
    description: Your description
    usage: /<command>
    permission: sonorous.command
    aliases: [ s, so ]